#!/bin/bash

trap 'kill 0' INT

root_dir=$(dirname ${BASH_SOURCE[0]})

if [ "$1" = init ]
then
    pushd "$root_dir/server" && { npm install; popd; }
    exit $?
fi

ws_port=8080

pushd "$root_dir/server"
adb_port=5555
node websocket-forward.js $ws_port $adb_port &
gp await-port $ws_port
popd

ws_url=`gp url $ws_port`
pushd "$root_dir/client"
sed 's,WEBSOCKET_URL,'${ws_url/http/ws}',g' adb.html > index.html

html_port=3000
# python3 -m http.server $html_port &
http-server -p $html_port &
gp await-port $html_port
echo "Open in new tab $(gp url $html_port)"

wait